---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: overseerr-tls
  namespace: media
spec:
  secretName: overseerr-tls
  issuerRef:
    name: cluster-ca
    kind: ClusterIssuer
  commonName: overseerr.homelab
  dnsNames:
    - overseerr.homelab
