---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: overseerr
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: "3.5.1"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 30m
  install:
    createNamespace: false
    remediation:
      retries: 3
    timeout: 15m
  upgrade:
    remediation:
      retries: 3
    timeout: 15m
  values:
    controllers:
      overseerr:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: sctx/overseerr
              tag: latest
            env:
              - name: PUID
                valueFrom:
                  configMapKeyRef:
                    name: overseerr-config
                    key: PUID
              - name: PGID
                valueFrom:
                  configMapKeyRef:
                    name: overseerr-config
                    key: PGID
              - name: TZ
                valueFrom:
                  configMapKeyRef:
                    name: overseerr-config
                    key: TZ
            resources:
              requests:
                cpu: "100m"
                memory: "256Mi"
              limits:
                cpu: "1000m"
                memory: "1Gi"

    service:
      app:
        controller: overseerr
        ports:
          http:
            port: 5055

    persistence:
      config:
        existingClaim: overseerr-config
        globalMounts:
          - path: /app/config

    defaultPodOptions:
      nodeSelector:
        kubernetes.io/hostname: rishik-worker1
