apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: intel-device-plugin-gpu
  namespace: kube-system
spec:
  interval: 10m
  dependsOn:
    - name: node-feature-discovery
      namespace: kube-system
    - name: intel-device-plugins-operator
      namespace: kube-system
  chart:
    spec:
      chart: intel-device-plugins-gpu
      version: "0.35.0"
      sourceRef:
        kind: HelmRepository
        name: intel
        namespace: flux-system
      interval: 10m
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    sharedDevNum: 4
    nodeSelector:
      intel.gpu: "true"
    resources:
      requests:
        cpu: "10m"
        memory: "32Mi"
      limits:
        cpu: "50m"
        memory: "64Mi"
