apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: intel-device-plugins-operator
  namespace: kube-system
spec:
  interval: 10m
  dependsOn:
    - name: node-feature-discovery
      namespace: kube-system
  chart:
    spec:
      chart: intel-device-plugins-operator
      version: "0.35.0"
      sourceRef:
        kind: HelmRepository
        name: intel
        namespace: flux-system
      interval: 10m
  install:
    createNamespace: false
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
