apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-root-media
spec:
  capacity:
    storage: 25Ti
  accessModes: [ReadWriteMany]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-media
  claimRef:
    namespace: media
    name: media-root
  mountOptions:
    - nfsvers=3
    - hard
    - nolock
    - noatime
    - _netdev
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: 192.168.1.215#/volume1/media#media-root-media
    volumeAttributes:
      server: 192.168.1.215
      share: /volume1/media
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-root-siloarr
spec:
  capacity:
    storage: 25Ti
  accessModes: [ReadWriteMany]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-media
  claimRef:
    namespace: siloarr
    name: media-root
  mountOptions:
    - nfsvers=3
    - hard
    - nolock
    - noatime
    - _netdev
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: 192.168.1.215#/volume1/media#media-root-siloarr
    volumeAttributes:
      server: 192.168.1.215
      share: /volume1/media
