apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: promtail
  namespace: monitoring
spec:
  interval: 10m
  dependsOn:
    - name: loki
      namespace: monitoring
  chart:
    spec:
      chart: promtail
      version: 6.15.4
      sourceRef:
        kind: HelmRepository
        name: grafana-promtail
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    config:
      clients:
        - url: http://loki.homelab:3100/loki/api/v1/push
