apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: plex-tls
  namespace: media
spec:
  secretName: plex-tls
  issuerRef:
    name: cluster-ca
    kind: ClusterIssuer
  commonName: plex.homelab
  dnsNames:
    - plex.homelab
