apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: plex-media-server
      version: "1.3.0"
      sourceRef:
        kind: HelmRepository
        name: plex
        namespace: flux-system
      interval: 30m
  install:
    createNamespace: false
    remediation:
      retries: 3
    timeout: 15m
  upgrade:
    remediation:
      retries: 3
    timeout: 15m
  values:
    nodeSelector:
      kubernetes.io/hostname: rishik-worker1

    pms:
      configExistingClaim: plex-config
      resources:
        requests:
          cpu: "500m"
          memory: "1Gi"
        limits:
          cpu: "4000m"
          memory: "4Gi"
          gpu.intel.com/i915: "1"
      livenessProbe:
        httpGet:
          path: /identity
          port: 32400
        initialDelaySeconds: 120
        periodSeconds: 30
        timeoutSeconds: 10
        failureThreshold: 7
      readinessProbe:
        httpGet:
          path: /identity
          port: 32400
        initialDelaySeconds: 60
        periodSeconds: 15
        timeoutSeconds: 10
        failureThreshold: 3

    initContainer:
      script: |-
        #!/bin/sh
        echo "waiting for pre-existing pms database to be uploaded..."

        if [ -d "/config/Library" ]; then
          echo "PMS library already exists, exiting."
          exit 0
        fi

        # wait for the database archive to be manually copied to the server
        while [ ! -f /pms.tgz ]; do sleep 2; done;

        tar -xvzf /pms.tgz -C /config
        rm /pms.tgz

        echo "Done."

    # Environment variables loaded from ConfigMap for filesystem permissions
    # PLEX_UID/PLEX_GID should match the ownership of the external HDD
    extraEnv:
      PLEX_CLAIM: ""

    # Reference ConfigMap for configurable values
    extraEnvFrom:
      - configMapRef:
          name: plex-config

    extraVolumes: []
    extraVolumeMounts: []

    service:
      type: LoadBalancer
      port: 32400
