apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config
  namespace: media
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-retain
  resources:
    requests:
      storage: 20Gi
