apiVersion: apps/v1
kind: Deployment
metadata:
  name: rreading-glasses-postgresql
  namespace: media
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: rreading-glasses-postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: postgresql
      app.kubernetes.io/instance: rreading-glasses-postgresql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgresql
        app.kubernetes.io/instance: rreading-glasses-postgresql
    spec:
      nodeSelector:
        kubernetes.io/hostname: rishik-worker1
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
      containers:
        - name: postgresql
          image: postgres:16-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              name: postgresql
              protocol: TCP
          env:
            - name: POSTGRES_DB
              value: rreading_glasses
            - name: POSTGRES_USER
              value: rreading_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rreading-glasses-credentials
                  key: POSTGRES_PASSWORD
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 999
            runAsGroup: 999
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - rreading_user
                - -d
                - rreading_glasses
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - rreading_user
                - -d
                - rreading_glasses
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: rreading-glasses-postgresql-data
---
apiVersion: v1
kind: Service
metadata:
  name: rreading-glasses-postgresql
  namespace: media
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: rreading-glasses-postgresql
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: rreading-glasses-postgresql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rreading-glasses-postgresql-data
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 8Gi
