apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sure-finance
  namespace: sure-finance
spec:
  interval: 30m
  chart:
    spec:
      chart: charts/maybe-finance
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 30m
  install:
    createNamespace: false
    remediation:
      retries: 3
    timeout: 10m
  upgrade:
    remediation:
      retries: 3
    timeout: 10m
  values:
    # Use Sure fork (community fork with SimpleFIN support)
    image:
      repository: ghcr.io/we-promise/sure
      tag: "v0.6.5-hotfix.1"

    # Enable OpenAI integration
    openai:
      enabled: true
      secretKey: openai-api-key
      model: gpt-5-mini

    # Enable SimpleFIN for bank sync
    simplefin:
      enabled: true
      secretKey: simplefin-access-url

    # PostgreSQL configuration
    postgresql:
      persistence:
        size: 4Gi

    # Resource limits
    resources:
      requests:
        cpu: "50m"
        memory: "256Mi"
      limits:
        cpu: "200m"
        memory: "512Mi"
