apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sure-finance
  namespace: sure-finance
spec:
  interval: 30m
  chart:
    spec:
      chart: charts/maybe-finance
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 30m
  install:
    createNamespace: false
    remediation:
      retries: 3
    timeout: 10m
  upgrade:
    remediation:
      retries: 3
    timeout: 10m
  values:
    # Use pinned version
    image:
      tag: "0.1.0-alpha.17"

    # PostgreSQL configuration
    postgresql:
      persistence:
        size: 4Gi

    # Resource limits
    resources:
      requests:
        cpu: "50m"
        memory: "256Mi"
      limits:
        cpu: "200m"
        memory: "512Mi"
