apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sure-finance
  namespace: sure-finance
spec:
  interval: 30m
  chart:
    spec:
      chart: maybe-finance
      version: 0.2.7
      sourceRef:
        kind: HelmRepository
        name: vicsufer
        namespace: flux-system
      interval: 30m
  install:
    createNamespace: false
    remediation:
      retries: 3
    timeout: 10m
  upgrade:
    remediation:
      retries: 3
    timeout: 10m
  values:
    replicaCount: 1

    service:
      type: ClusterIP

    deployment:
      repository: ghcr.io/maybe-finance/maybe
      tag: 0.5.0
      port: 3000
      pullPolicy: IfNotPresent
      extraEnvVarsSecret: sure-credentials
      env:
        - name: SELF_HOSTING_ENABLED
          value: "true"
        - name: REDIS_HOST
          value: "sure-finance-redis"
        - name: REDIS_PORT
          value: "6379"

    # PostgreSQL configuration with Longhorn storage
    postgresql:
      enabled: true
      primary:
        persistence:
          enabled: true
          size: 4Gi
          storageClass: longhorn
          accessMode: ReadWriteOnce
      auth:
        username: maybe
        database: maybe
        existingSecret: sure-credentials
        secretKeys:
          adminPasswordKey: postgres-password
          userPasswordKey: postgres-password
      resources:
        requests:
          cpu: "50m"
          memory: "128Mi"
        limits:
          cpu: "200m"
          memory: "256Mi"

    # Redis - disabled, using external Redis deployment due to chart bug
    redis:
      enabled: false

    # Application storage with Longhorn
    storage:
      enabled: true
      storageClass: longhorn
      accessMode: ReadWriteOnce
      size: 2Gi

    # Disable built-in ingress - we'll create our own
    ingress:
      create: false

    resources:
      requests:
        cpu: "50m"
        memory: "256Mi"
      limits:
        cpu: "200m"
        memory: "512Mi"

  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: sure-finance
            patch: |
              - op: remove
                path: /spec/template/spec/containers/0/env/4
              - op: add
                path: /spec/template/spec/containers/0/env/-
                value:
                  name: REDIS_URL
                  value: "redis://sure-finance-redis:6379/0"
