---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: calibre-converter
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: "3.5.1"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 30m
  install:
    createNamespace: false
    remediation:
      retries: 3
    timeout: 15m
  upgrade:
    remediation:
      retries: 3
    timeout: 15m
  values:
    controllers:
      calibre-converter:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: ghcr.io/blazepower/calibre-converter
              tag: v1.0.0
            env:
              - name: WATCH_PATH
                valueFrom:
                  configMapKeyRef:
                    name: calibre-converter-config
                    key: WATCH_PATH
              - name: SCAN_INTERVAL
                valueFrom:
                  configMapKeyRef:
                    name: calibre-converter-config
                    key: SCAN_INTERVAL
              - name: MAX_CONCURRENT
                valueFrom:
                  configMapKeyRef:
                    name: calibre-converter-config
                    key: MAX_CONCURRENT
              - name: DATABASE_PATH
                valueFrom:
                  configMapKeyRef:
                    name: calibre-converter-config
                    key: DATABASE_PATH
              - name: INPUT_EXTENSIONS
                valueFrom:
                  configMapKeyRef:
                    name: calibre-converter-config
                    key: INPUT_EXTENSIONS
              - name: OUTPUT_FORMAT
                valueFrom:
                  configMapKeyRef:
                    name: calibre-converter-config
                    key: OUTPUT_FORMAT
              - name: MIN_OUTPUT_SIZE
                valueFrom:
                  configMapKeyRef:
                    name: calibre-converter-config
                    key: MIN_OUTPUT_SIZE
              - name: STABILITY_WAIT
                valueFrom:
                  configMapKeyRef:
                    name: calibre-converter-config
                    key: STABILITY_WAIT
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              runAsNonRoot: true
              runAsUser: 1000
              runAsGroup: 1000
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: "100m"
                memory: "256Mi"
              limits:
                cpu: "2000m"
                memory: "2Gi"

    persistence:
      data:
        existingClaim: calibre-converter-data
        globalMounts:
          - path: /data
      media:
        type: hostPath
        hostPath: /media/rishik/Expansion
        globalMounts:
          - path: /media
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp

    defaultPodOptions:
      nodeSelector:
        kubernetes.io/hostname: rishik-worker1
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
