values:
  deploymentMode: SingleBinary

  loki:
    storage:
      type: filesystem
    auth_enabled: false

    commonConfig:
      replication_factor: 1

    limits_config:
      retention_period: 720h

    compactor:
      retention_enabled: true
      retention_delete_delay: 2h
      delete_request_store: filesystem

    # Correct modern schema config block
    schema_config:
      configs:
        - from: "2024-04-01"
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: loki_index_
            period: 24h

  singleBinary:
    replicas: 1
    persistence:
      enabled: true
      size: 10Gi
      storageClass: longhorn

    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi

    extraArgs:
      - -config.expand-env=true

    livenessProbe:
      httpGet:
        path: /ready
        port: http-metrics
      initialDelaySeconds: 45

    readinessProbe:
      httpGet:
        path: /ready
        port: http-metrics
      initialDelaySeconds: 45

  backend:
    replicas: 0
  read:
    replicas: 0
  write:
    replicas: 0

  gateway:
    enabled: false
  chunksCache:
    enabled: false
  resultsCache:
    enabled: false
  lokiCanary:
    enabled: false
  test:
    enabled: false
