---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bookshelf
  namespace: media
spec:
  suspend: false
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: "3.7.3"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 30m
  install:
    createNamespace: false
    remediation:
      retries: 3
    timeout: 15m
  upgrade:
    remediation:
      retries: 3
    timeout: 15m
  values:
    controllers:
      bookshelf:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: ghcr.io/pennydreadful/bookshelf
              tag: hardcover-v0.4.20.91
            env:
              - name: PUID
                valueFrom:
                  configMapKeyRef:
                    name: bookshelf-config
                    key: PUID
              - name: PGID
                valueFrom:
                  configMapKeyRef:
                    name: bookshelf-config
                    key: PGID
              - name: TZ
                valueFrom:
                  configMapKeyRef:
                    name: bookshelf-config
                    key: TZ
            securityContext:
              allowPrivilegeEscalation: true
              readOnlyRootFilesystem: false
              runAsNonRoot: false
              capabilities:
                drop:
                  - ALL
                add:
                  - CHOWN
                  - SETUID
                  - SETGID
            resources:
              requests:
                cpu: "100m"
                memory: "256Mi"
              limits:
                cpu: "1000m"
                memory: "1Gi"

    service:
      app:
        controller: bookshelf
        ports:
          http:
            port: 8787

    persistence:
      config:
        existingClaim: bookshelf-config
        globalMounts:
          - path: /config
      media:
        type: hostPath
        hostPath: /media/rishik/Expansion
        globalMounts:
          - path: /media

    defaultPodOptions:
      nodeSelector:
        kubernetes.io/hostname: rishik-worker1
      securityContext:
        fsGroup: 1000
