apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: kyverno-admission-pdb
  namespace: kyverno
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app.kubernetes.io/name: kyverno
      app.kubernetes.io/component: admission-controller
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: kyverno-background-pdb
  namespace: kyverno
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app.kubernetes.io/name: kyverno
      app.kubernetes.io/component: background-controller
