apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: metallb-controller-pdb
  namespace: metallb-system
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app.kubernetes.io/name: metallb
      app.kubernetes.io/component: controller
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: metallb-speaker-pdb
  namespace: metallb-system
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app.kubernetes.io/name: metallb
      app.kubernetes.io/component: speaker
