apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cert-manager-pdb
  namespace: cert-manager
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app.kubernetes.io/name: cert-manager
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cert-manager-webhook-pdb
  namespace: cert-manager
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app.kubernetes.io/name: webhook
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cert-manager-cainjector-pdb
  namespace: cert-manager
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app.kubernetes.io/name: cainjector
