apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: loki-pdb
  namespace: monitoring
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app.kubernetes.io/name: loki
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: promtail-pdb
  namespace: monitoring
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app.kubernetes.io/name: promtail
