apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sealed-secrets-pdb
  namespace: flux-system
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app.kubernetes.io/name: sealed-secrets
