apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-resources-limits
  annotations:
    policies.kyverno.io/title: Require Resource Requests and Limits
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/description: >-
      Ensure all containers have CPU and memory requests and limits defined
      to prevent resource starvation and ensure proper scheduling in the
      RKE2 cluster with Longhorn storage.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: validate-resources
      match:
        any:
          - resources:
              kinds:
                - Pod
      exclude:
        any:
          - resources:
              namespaces:
                - kube-system
                - kube-node-lease
                - kube-public
                - flux-system
                - kyverno
                - longhorn-system
                - storage
                - monitoring
                - cert-manager
      validate:
        message: >-
          All containers must have CPU and memory requests and limits defined.
          Container '{{element.name}}' is missing required resource specifications.
        foreach:
          - list: "request.object.spec.containers"
            deny:
              conditions:
                any:
                  - key: "{{ element.resources.requests.memory || '' }}"
                    operator: Equals
                    value: ""
                  - key: "{{ element.resources.requests.cpu || '' }}"
                    operator: Equals
                    value: ""
                  - key: "{{ element.resources.limits.memory || '' }}"
                    operator: Equals
                    value: ""
                  - key: "{{ element.resources.limits.cpu || '' }}"
                    operator: Equals
                    value: ""
