---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: radarr-tls
  namespace: media
spec:
  secretName: radarr-tls
  issuerRef:
    name: cluster-ca
    kind: ClusterIssuer
  commonName: radarr.homelab
  dnsNames:
    - radarr.homelab
