---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: calibre-web
  namespace: media
spec:
  suspend: false
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: "3.5.1"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 30m
  install:
    createNamespace: false
    remediation:
      retries: 3
    timeout: 15m
  upgrade:
    remediation:
      retries: 3
    timeout: 15m
  values:
    controllers:
      calibre-web:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: lscr.io/linuxserver/calibre-web
              tag: "0.6.25"
            env:
              - name: PUID
                valueFrom:
                  configMapKeyRef:
                    name: calibre-web-config
                    key: PUID
              - name: PGID
                valueFrom:
                  configMapKeyRef:
                    name: calibre-web-config
                    key: PGID
              - name: TZ
                valueFrom:
                  configMapKeyRef:
                    name: calibre-web-config
                    key: TZ
            securityContext:
              allowPrivilegeEscalation: true
              readOnlyRootFilesystem: false
              runAsNonRoot: false
              runAsUser: 0
              runAsGroup: 0
              capabilities:
                drop:
                  - ALL
                add:
                  - CHOWN
                  - SETUID
                  - SETGID
            resources:
              requests:
                cpu: "100m"
                memory: "256Mi"
              limits:
                cpu: "500m"
                memory: "512Mi"

    service:
      app:
        controller: calibre-web
        ports:
          http:
            port: 8083

    persistence:
      config:
        existingClaim: calibre-web-config
        globalMounts:
          - path: /config
      media:
        type: hostPath
        hostPath: /media/rishik/Expansion
        globalMounts:
          - path: /media

    defaultPodOptions:
      nodeSelector:
        kubernetes.io/hostname: rishik-worker1
      securityContext:
        fsGroup: 1000
