apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: adguard-home
  namespace: adguard-home
spec:
  interval: 30m
  chart:
    spec:
      chart: charts/adguard-home
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 30m
  install:
    createNamespace: false
    remediation:
      retries: 3
    timeout: 10m
  upgrade:
    remediation:
      retries: 3
    timeout: 10m
  values:
    persistence:
      config:
        enabled: true
        size: 1Gi
      work:
        enabled: true
        size: 2Gi
    resources:
      requests:
        cpu: "50m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"
