apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: block-risky-capabilities
  annotations:
    policies.kyverno.io/title: Block Risky Security Capabilities
    policies.kyverno.io/category: Pod Security
    policies.kyverno.io/severity: high
    policies.kyverno.io/description: >-
      Disallow hostPath volumes, privileged containers, and hostNetwork
      in user namespaces to maintain cluster security. Infrastructure
      namespaces are excluded to allow system components to function.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: deny-privileged-containers
      match:
        any:
          - resources:
              kinds:
                - Pod
      exclude:
        any:
          - resources:
              namespaces:
                - kube-system
                - kube-node-lease
                - kube-public
                - flux-system
                - kyverno
                - longhorn-system
                - storage
                - monitoring
                - cert-manager
      validate:
        message: >-
          Privileged containers are not allowed in user namespaces.
        foreach:
          - list: "request.object.spec.containers"
            deny:
              conditions:
                all:
                  - key: "{{ element.securityContext.privileged || false }}"
                    operator: Equals
                    value: true
          - list: "request.object.spec.initContainers || []"
            deny:
              conditions:
                all:
                  - key: "{{ element.securityContext.privileged || false }}"
                    operator: Equals
                    value: true
          - list: "request.object.spec.ephemeralContainers || []"
            deny:
              conditions:
                all:
                  - key: "{{ element.securityContext.privileged || false }}"
                    operator: Equals
                    value: true
    - name: deny-host-network
      match:
        any:
          - resources:
              kinds:
                - Pod
      exclude:
        any:
          - resources:
              namespaces:
                - kube-system
                - kube-node-lease
                - kube-public
                - flux-system
                - kyverno
                - longhorn-system
                - storage
                - monitoring
                - cert-manager
      validate:
        message: "hostNetwork is not allowed in user namespaces."
        pattern:
          spec:
            =(hostNetwork): false
    - name: deny-host-path-volumes
      match:
        any:
          - resources:
              kinds:
                - Pod
      exclude:
        any:
          - resources:
              namespaces:
                - kube-system
                - kube-node-lease
                - kube-public
                - flux-system
                - kyverno
                - longhorn-system
                - storage
                - monitoring
                - cert-manager
      validate:
        message: "hostPath volumes are not allowed in user namespaces."
        pattern:
          spec:
            =(volumes):
              - X(hostPath): "null"
