---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sabnzbd
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: "3.5.1"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 30m
  install:
    createNamespace: false
    remediation:
      retries: 3
    timeout: 15m
  upgrade:
    remediation:
      retries: 3
    timeout: 15m
  values:
    controllers:
      sabnzbd:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: lscr.io/linuxserver/sabnzbd
              tag: "4.5.5"
            env:
              - name: PUID
                valueFrom:
                  configMapKeyRef:
                    name: sabnzbd-config
                    key: PUID
              - name: PGID
                valueFrom:
                  configMapKeyRef:
                    name: sabnzbd-config
                    key: PGID
              - name: TZ
                valueFrom:
                  configMapKeyRef:
                    name: sabnzbd-config
                    key: TZ
            # Probes to detect hangs and restart automatically
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /sabnzbd/api?mode=version
                    port: 8080
                  initialDelaySeconds: 30
                  periodSeconds: 30
                  timeoutSeconds: 10
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /sabnzbd/api?mode=version
                    port: 8080
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 3
            resources:
              requests:
                cpu: "200m"
                memory: "512Mi"
              limits:
                cpu: "2000m"
                memory: "2Gi"

    service:
      app:
        controller: sabnzbd
        ports:
          http:
            port: 8080

    persistence:
      config:
        existingClaim: sabnzbd-config
        globalMounts:
          - path: /config
      media:
        type: hostPath
        hostPath: /media/rishik/Expansion
        globalMounts:
          - path: /media

    defaultPodOptions:
      nodeSelector:
        kubernetes.io/hostname: rishik-worker1
