apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kyverno-policies
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: kyverno-install
  path: ./infrastructure/policies/kyverno-policies
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m
