---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cooklang
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: charts/cooklang
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 30m
  install:
    createNamespace: false
    remediation:
      retries: 3
    timeout: 10m
  upgrade:
    remediation:
      retries: 3
    timeout: 10m
  values:
    image:
      repository: ghcr.io/blazepower/cooklang
      tag: "0.21.0"
    
    persistence:
      hostPath: /home/rishik/recipes
    
    # Run as rishik user (UID 1000) to match host folder permissions
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    
    podSecurityContext:
      fsGroup: 1000
    
    nodeSelector:
      kubernetes.io/hostname: rishik-worker1
    
    env:
      TZ: America/Los_Angeles
    
    # Cook Cloud Sync
    sync:
      enabled: true
      image:
        repository: ghcr.io/blazepower/cook-sync
        tag: "0.2.5"
        pullPolicy: Always
      vnc:
        enabled: true  # Set to false after initial OTP login
      novnc:
        enabled: true  # Web-based VNC access via browser
