---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cooklang
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: charts/cooklang
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 30m
  install:
    createNamespace: false
    remediation:
      retries: 3
    timeout: 10m
  upgrade:
    remediation:
      retries: 3
    timeout: 10m
  values:
    image:
      repository: ghcr.io/blazepower/cooklang
      tag: "0.21.0"
    
    nodeSelector:
      kubernetes.io/hostname: rishik-worker1
    
    env:
      TZ: America/Los_Angeles
