---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: whisparr
  namespace: siloarr
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: "4.6.2"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 30m
  install:
    createNamespace: false
    remediation:
      retries: 3
    timeout: 15m
  upgrade:
    remediation:
      retries: 3
    timeout: 15m
  values:
    controllers:
      whisparr:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: ghcr.io/hotio/whisparr
              tag: v3
            env:
              - name: PUID
                valueFrom:
                  configMapKeyRef:
                    name: whisparr-config
                    key: PUID
              - name: PGID
                valueFrom:
                  configMapKeyRef:
                    name: whisparr-config
                    key: PGID
              - name: TZ
                valueFrom:
                  configMapKeyRef:
                    name: whisparr-config
                    key: TZ
            resources:
              requests:
                cpu: "100m"
                memory: "256Mi"
              limits:
                cpu: "1000m"
                memory: "1Gi"

    service:
      app:
        controller: whisparr
        ports:
          http:
            port: 6969

    persistence:
      config:
        existingClaim: whisparr-config
        globalMounts:
          - path: /config
      media:
        type: hostPath
        hostPath: /media/rishik/Expansion
        globalMounts:
          - path: /media

    defaultPodOptions:
      nodeSelector:
        kubernetes.io/hostname: rishik-worker1
