apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: storage
spec:
  interval: 10m
  chart:
    spec:
      chart: longhorn
      # optionally pin: version: 1.7.2
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      interval: 10m
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    persistence:
      defaultClass: true
      defaultClassReplicaCount: 1
    defaultSettings:
      defaultDataPath: "/var/lib/longhorn"
      # Minimum CPU percentage guaranteed for instance managers (5%)
      guaranteedInstanceManagerCPU: 5
    longhornManager:
      resources:
        requests:
          cpu: "25m"
          memory: "64Mi"
        limits:
          cpu: "200m"
          memory: "256Mi"
    longhornDriver:
      resources:
        requests:
          cpu: "25m"
          memory: "64Mi"
        limits:
          cpu: "200m"
          memory: "256Mi"
    longhornUI:
      resources:
        requests:
          cpu: "25m"
          memory: "32Mi"
        limits:
          cpu: "100m"
          memory: "128Mi"
