apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: storage
spec:
  interval: 10m
  chart:
    spec:
      chart: longhorn
      # optionally pin: version: 1.7.2
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      interval: 10m
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    persistence:
      defaultClass: true
      defaultClassReplicaCount: 1
    defaultSettings:
      defaultDataPath: "/var/lib/longhorn"
