apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: storage
  annotations:
    # Force reconciliation by updating this annotation
    reconcile.fluxcd.io/requestedAt: "2025-11-29T00:00:00Z"
spec:
  interval: 10m
  timeout: 15m
  chart:
    spec:
      chart: longhorn
      version: "1.10.x"  # Pin to 1.10.x to avoid unexpected upgrades
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      interval: 10m
  install:
    createNamespace: false
    remediation:
      retries: 5
  upgrade:
    # Clean up failed releases before retrying
    cleanupOnFail: true
    remediation:
      retries: 5
      # Remediate the last failure instead of trying to uninstall
      remediateLastFailure: true
      strategy: rollback
  # Prevent Flux from trying to uninstall on failure
  uninstall:
    keepHistory: false
    timeout: 10m
  values:
    persistence:
      defaultClass: true
      defaultClassReplicaCount: 1
    defaultSettings:
      defaultDataPath: "/var/lib/longhorn"
      guaranteedInstanceManagerCPU: 5
      concurrentAutomaticEngineUpgradePerNodeLimit: 1
      backupTarget: ""
      backupTargetCredentialSecret: ""
      replicaAutoBalance: "disabled"
      storageMinimalAvailablePercentage: 15
      orphanAutoDeletion: true
      # Remove or set to false - this can interfere with Helm operations
      # deleting-confirmation-flag: true
    longhornManager:
      priorityClass: system-critical
      resources:
        requests:
          cpu: "25m"
          memory: "64Mi"
        limits:
          cpu: "200m"
          memory: "256Mi"
    longhornDriver:
      priorityClass: system-critical
      resources:
        requests:
          cpu: "25m"
          memory: "64Mi"
        limits:
          cpu: "200m"
          memory: "256Mi"
    longhornUI:
      resources:
        requests:
          cpu: "25m"
          memory: "32Mi"
        limits:
          cpu: "100m"
          memory: "128Mi"
