---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prowlarr-tls
  namespace: media
spec:
  secretName: prowlarr-tls
  issuerRef:
    name: cluster-ca
    kind: ClusterIssuer
  commonName: prowlarr.homelab
  dnsNames:
    - prowlarr.homelab
