---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bazarr-tls
  namespace: media
spec:
  secretName: bazarr-tls
  issuerRef:
    name: cluster-ca
    kind: ClusterIssuer
  commonName: bazarr.homelab
  dnsNames:
    - bazarr.homelab
