---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bazarr
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: "4.6.2"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 30m
  install:
    createNamespace: false
    remediation:
      retries: 3
    timeout: 15m
  upgrade:
    remediation:
      retries: 3
    timeout: 15m
  values:
    controllers:
      bazarr:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: lscr.io/linuxserver/bazarr
              tag: "1.5.4"
            env:
              - name: PUID
                valueFrom:
                  configMapKeyRef:
                    name: bazarr-config
                    key: PUID
              - name: PGID
                valueFrom:
                  configMapKeyRef:
                    name: bazarr-config
                    key: PGID
              - name: TZ
                valueFrom:
                  configMapKeyRef:
                    name: bazarr-config
                    key: TZ
            resources:
              requests:
                cpu: "100m"
                memory: "256Mi"
              limits:
                cpu: "1000m"
                memory: "1Gi"

    service:
      app:
        controller: bazarr
        ports:
          http:
            port: 6767

    persistence:
      config:
        existingClaim: bazarr-config
        globalMounts:
          - path: /config
      media:
        type: hostPath
        hostPath: /media/rishik/Expansion
        globalMounts:
          - path: /media

    defaultPodOptions:
      nodeSelector:
        kubernetes.io/hostname: rishik-worker1
