apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  interval: 5m
  chart:
    spec:
      chart: tailscale-operator
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: flux-system
      version: "1.94.2"
  valuesFrom:
    - kind: Secret
      name: tailscale-auth
      valuesKey: TS_CLIENT_ID
      targetPath: oauth.clientId
    - kind: Secret
      name: tailscale-auth
      valuesKey: TS_CLIENT_SECRET
      targetPath: oauth.clientSecret
  values:
    operator:
      logLevel: "info"

