apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  interval: 5m
  chart:
    spec:
      chart: operator
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: flux-system
      version: "0.1.82"  # pin this
  values:
    oauth:
      clientId: $TS_CLIENT_ID
      clientSecret: $TS_CLIENT_SECRET
    operator:
      logLevel: "info"

