---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: qbittorrent-tls
  namespace: media
spec:
  secretName: qbittorrent-tls
  issuerRef:
    name: cluster-ca
    kind: ClusterIssuer
  commonName: qbittorrent.homelab
  dnsNames:
    - qbittorrent.homelab
