---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: "3.5.1"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 30m
  install:
    createNamespace: false
    remediation:
      retries: 3
    timeout: 15m
  upgrade:
    remediation:
      retries: 3
    timeout: 15m
  values:
    controllers:
      qbittorrent:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          gluetun:
            image:
              repository: qmcgaw/gluetun
              tag: v3
            env:
              - name: VPN_SERVICE_PROVIDER
                value: "protonvpn"
              - name: VPN_TYPE
                value: "wireguard"
              - name: VPN_PORT_FORWARDING
                value: "on"
              - name: VPN_PORT_FORWARDING_PROVIDER
                value: "protonvpn"
              - name: PORT_FORWARD_ONLY
                value: "true"
              - name: SERVER_COUNTRIES
                value: "United States"
              - name: SERVER_CITIES
                value: "Seattle"
              - name: WIREGUARD_PRIVATE_KEY
                valueFrom:
                  secretKeyRef:
                    name: qbittorrent-vpn
                    key: WIREGUARD_PRIVATE_KEY
              - name: WIREGUARD_ADDRESSES
                valueFrom:
                  secretKeyRef:
                    name: qbittorrent-vpn
                    key: WIREGUARD_ADDRESSES
              - name: TZ
                valueFrom:
                  configMapKeyRef:
                    name: qbittorrent-config
                    key: TZ
              - name: FIREWALL_INPUT_PORTS
                value: "8080"
              - name: FIREWALL_OUTBOUND_SUBNETS
                value: "10.42.0.0/16,10.43.0.0/16"
              - name: UPDATER_PERIOD
                value: "24h"
              - name: HTTPPROXY
                value: "off"
            securityContext:
              capabilities:
                add:
                  - NET_ADMIN
            resources:
              requests:
                cpu: "50m"
                memory: "128Mi"
              limits:
                cpu: "500m"
                memory: "512Mi"

          app:
            dependsOn: gluetun
            image:
              repository: lscr.io/linuxserver/qbittorrent
              tag: "5.1.4"
            env:
              - name: PUID
                valueFrom:
                  configMapKeyRef:
                    name: qbittorrent-config
                    key: PUID
              - name: PGID
                valueFrom:
                  configMapKeyRef:
                    name: qbittorrent-config
                    key: PGID
              - name: TZ
                valueFrom:
                  configMapKeyRef:
                    name: qbittorrent-config
                    key: TZ
              - name: WEBUI_PORT
                value: "8080"
            resources:
              requests:
                cpu: "100m"
                memory: "256Mi"
              limits:
                cpu: "2000m"
                memory: "2Gi"

          # Syncs VPN IP with MAM dynamic seedbox and qBittorrent port
          vpn-sync:
            dependsOn: gluetun
            image:
              repository: alpine
              tag: "3.21"
            env:
              - name: MAM_ID
                valueFrom:
                  secretKeyRef:
                    name: mam-credentials
                    key: MAM_ID
            command:
              - /bin/sh
              - -c
              - |
                echo "Waiting for gluetun..."
                while [ ! -f /tmp/gluetun/forwarded_port ]; do sleep 5; done
                until wget -qO- http://localhost:8080/api/v2/app/version >/dev/null 2>&1; do sleep 5; done
                LAST_IP="" LAST_PORT=""
                while true; do
                  IP=$(wget -qO- http://localhost:8000/v1/publicip/ip 2>/dev/null | tr -d '"')
                  PORT=$(cat /tmp/gluetun/forwarded_port 2>/dev/null)
                  # Sync qBittorrent port
                  if [ -n "$PORT" ] && [ "$PORT" != "$LAST_PORT" ]; then
                    echo "Setting qBittorrent port to $PORT"
                    wget -qO- --post-data="json={\"listen_port\":$PORT}" http://localhost:8080/api/v2/app/setPreferences
                    LAST_PORT="$PORT"
                  fi
                  # Sync MAM dynamic seedbox IP
                  if [ -n "$IP" ] && [ "$IP" != "$LAST_IP" ]; then
                    echo "Updating MAM seedbox IP to $IP"
                    RESP=$(wget -qO- --header="Cookie: mam_id=$MAM_ID" \
                      "https://t.myanonamouse.net/json/dynamicSeedbox.php" 2>&1)
                    echo "MAM response: $RESP"
                    LAST_IP="$IP"
                  fi
                  sleep 300
                done
            resources:
              requests:
                cpu: "5m"
                memory: "16Mi"
              limits:
                cpu: "50m"
                memory: "32Mi"

    service:
      app:
        controller: qbittorrent
        ports:
          http:
            port: 8080

    persistence:
      config:
        existingClaim: qbittorrent-config
        advancedMounts:
          qbittorrent:
            app:
              - path: /config
      media:
        type: hostPath
        hostPath: /media/rishik/Expansion
        advancedMounts:
          qbittorrent:
            app:
              - path: /media
      gluetun-data:
        type: emptyDir
        advancedMounts:
          qbittorrent:
            gluetun:
              - path: /tmp/gluetun
            vpn-sync:
              - path: /tmp/gluetun
                readOnly: true

    defaultPodOptions:
      nodeSelector:
        kubernetes.io/hostname: rishik-worker1
