---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: "3.5.1"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 30m
  install:
    createNamespace: false
    remediation:
      retries: 3
    timeout: 15m
  upgrade:
    remediation:
      retries: 3
    timeout: 15m
  values:
    controllers:
      qbittorrent:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          gluetun:
            image:
              repository: qmcgaw/gluetun
              tag: v3
            env:
              - name: VPN_SERVICE_PROVIDER
                value: "protonvpn"
              - name: VPN_TYPE
                value: "wireguard"
              - name: VPN_PORT_FORWARDING
                value: "on"
              - name: VPN_PORT_FORWARDING_PROVIDER
                value: "protonvpn"
              - name: PORT_FORWARD_ONLY
                value: "true"
              - name: SERVER_COUNTRIES
                value: "United States"
              - name: SERVER_CITIES
                value: "Seattle"
              - name: WIREGUARD_PRIVATE_KEY
                valueFrom:
                  secretKeyRef:
                    name: qbittorrent-vpn
                    key: WIREGUARD_PRIVATE_KEY
              - name: WIREGUARD_ADDRESSES
                valueFrom:
                  secretKeyRef:
                    name: qbittorrent-vpn
                    key: WIREGUARD_ADDRESSES
              - name: TZ
                valueFrom:
                  configMapKeyRef:
                    name: qbittorrent-config
                    key: TZ
              - name: FIREWALL_INPUT_PORTS
                value: "8080"
              - name: FIREWALL_OUTBOUND_SUBNETS
                value: "10.42.0.0/16,10.43.0.0/16"
              - name: UPDATER_PERIOD
                value: "24h"
              - name: HTTPPROXY
                value: "off"
            securityContext:
              capabilities:
                add:
                  - NET_ADMIN
            resources:
              requests:
                cpu: "50m"
                memory: "128Mi"
              limits:
                cpu: "500m"
                memory: "512Mi"

          app:
            dependsOn: gluetun
            image:
              repository: lscr.io/linuxserver/qbittorrent
              tag: "5.1.4"
            env:
              - name: PUID
                valueFrom:
                  configMapKeyRef:
                    name: qbittorrent-config
                    key: PUID
              - name: PGID
                valueFrom:
                  configMapKeyRef:
                    name: qbittorrent-config
                    key: PGID
              - name: TZ
                valueFrom:
                  configMapKeyRef:
                    name: qbittorrent-config
                    key: TZ
              - name: WEBUI_PORT
                value: "8080"
            resources:
              requests:
                cpu: "100m"
                memory: "256Mi"
              limits:
                cpu: "2000m"
                memory: "2Gi"

    service:
      app:
        controller: qbittorrent
        ports:
          http:
            port: 8080

    persistence:
      config:
        existingClaim: qbittorrent-config
        globalMounts:
          - path: /config
      media:
        type: hostPath
        hostPath: /media/rishik/Expansion
        globalMounts:
          - path: /media

    defaultPodOptions:
      nodeSelector:
        kubernetes.io/hostname: rishik-worker1
