---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mam-credentials
  namespace: media
spec:
  encryptedData:
    MAM_ID: AgAmmk1yHfJuGJUWaAB9eag3+m8SIJGTpuoGOzsfnR/OuQVxy+gBtwLMpyqKr7TnXidCr0v+slyx2Zfw1WdOGNSNKs3svjyLpXEMZZzh0ivd3JxG3uC1Ir3eg9UNY2jEEX3T2bVsIEhX5U+jDORQY37hMjxOxGVYDccFVqfb/CHW7SwClG4cKsbhnjXABT8E077tzzptEEnQuxAyEicQBWK6YlnrwwSy39bH8XQVvTbua+XWPfQdnuMk58cr9EpuA4CvYEH+jeXmHpN5jhFTnyPDXdkk7WTmRDkdmmwflMCoXhrVBCUCUq/SYn5biDVMhOut/YllTRQe5QWKq/zWlBzcFFkqFdTWP6pK6HE0xGsW6Y3azpg+Fqrg+RBHQSjMnWGE5YvYrqrXYXPjEWBAZZEP4aMHZYm9k9fwIN15zOz32q751yURlZJdeztrEIlMUA88UPDfAGtneO2y6Dt+9B+lM9FvkIGc7nadfPPrqprlHgJZulkdIxtuY9zgPpkiAvGLqxaVDKnkWswqBs7LP+uhUEqnZGLfv1PAhMZnfHeGn/Cw/6OxVyR2T64ODTe9hxcaWBOK1CJGqNmGxX84qgHgAngj0hb8anWmyA1GI/Y29kzNJxhU4hzadWqR8iePwohpFCu09nS05VWLIDcPMe8Gz/gZUo+5YQbq3LojeHtbAGeE+ZdX715y/Et2wPiZc0t44j/8hUf6jdSb0K+w6B9w5uylkTD27bNCo6kd8CqFnzZKCovEcAMZ1vjNEg3iTzUVD07Tg8L5+klr61mwZXT9LECNfwehY8r/INZG1oIufXvBe7Yw4fXjydr/lBEW07vRYDQUQmtxYL/nh2CbVnp47EW3tHpETAYVf3YVrF2p6RcVAnlHSaq6PWg70vKi9db0vlhPXrBw0t3eDD/SHGEeyRFupEor2rU76eplpmZX4DmttAzbNR9rNyhfRwDhQqq1laoIJAM+lTXc9db1gYVJ+ueWXWcsbkQSOkQ0bqmHh4b6TnT3X5C+moTFDqSNI2At5MU5RKPXCfLOXJzliJB2BdaISKEav8rKlQ4Q5dfVg8Xev4/jtYHPO69CRIenxzswGMDG
  template:
    metadata:
      name: mam-credentials
      namespace: media
    type: Opaque
