---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: qbittorrent-vpn
  namespace: media
spec:
  encryptedData:
    WIREGUARD_ADDRESSES: AgB+h2fH4cg31yke1Jt4FhY8q4LrYDRWFrwnzE7OgzPC6z0fVApqks8BkErr5SIukZA+61XENkb8ZjKRGtzmy7iOf2Ox8Jt8/kJZD0+MG9Y9WSdlMJykH/JPYkgTlNXoY/ebfXkX72SVdHZoMJUyoo4ikf6J7SA1i0ykVdlT3qKTZCcqA3LmtTkgozUaRctr1IVTWTkYnr6RNdKHMbo/aupOEBVFx3n191c+qV0og5OuC1rR4NM5ZRED7NEIfccduTAJIxqz7mXqM/4otQawNsgUoHX/Ng192a5sn/uC1cgNB4X0amaoAiNv2RXyEzsfB+dEt4HoureQikFE5dlvJSJUc86P1V4SyAdOuA95S2JwH1FCt7LAxDckrIjmLEXVijExA8G56DDvEN8HyRYbmQZQLyZJCcIVu25vbiFP/w4R5lSaX2bv0NW4Hc9zyVEMiozWhu1jCAoxp5w3bocIVqlDgu8AUbbNB2eGIUg6ZWDZ196hCyQajyrE2wBH4mMkydbKt59qpFJr5vSOpU8wi2fbtkgJDinZ8GhtrFdunHkBTHLwvD9S3NL2d8Zsylk0cwFkwRzJ05P9bJqGeKz6DgWBtLkOr9i1ZCur7LgwM6pO0bl4SucYQceXpkUfLeNnoS5vuJamIA++k2tOCmnG6MaAQhSaSICZdBlD9fpSKM6+ksd4TN31X8Cx286OgJcmm/D+NKJA32hU1pMc7A==
    WIREGUARD_PRIVATE_KEY: AgB+rdkXA+fAzR5rDF+4Le0P5TYgoeATS569PLfKqsL7jaouscH/Dw3ownitlCsaTcy/Q6b3gp5f0hT6EJdrIxsKT+uc7joHai19k4/E8jtZ/ALcxbJM19sqM16vq6fh/bCxlKbhoq6Mc7+zWveoFldndtlRLhFqUIwkowlLldGYCi4a0LtdBqiv8oNEYhpILceVDiM/TZPBp5H8CIXRY6sjUzCDJYDWnrH5l7H6ggdH8zpLNo0wgN4RcMVMjPzrzDK+DEuIsko7ZRK3tUnPFK5tQwSuXOivrcQw5F2si13l68jyRs9j9Ay30hD8FYOy8THnCtOAnDc/Ovx6EW4UI6zCdWywE5X8of3NVmO9nVWjSaUY6PyfjMuuY8SVCShPWluPDxFBWk2wMtGacEt4yU4CVV8sCeZmOHcJfFekrQB5b33MS627P+jX5kOV8YZ9QxQvZAbRnO6Bn8Gyi05DxC9uZJVxPfqPIMk5x/7s8AdagCMx6CpdYuhr4emZzALXwsDyqNFinc0RObOie6ha/nNOeJjS96tBz4oK2o1KAO23b/tU0lPLBUOK85dzxjP9PLYE6iLzWvAUtyN/qa+Eqf+X0mI8RVreATweIFn4793P0D31DuAggM6QInRhy7yBdu3pJtDIrAOvsdvKLYMwe4PbNnV/rxin1/TF4Cpj2mN+LKVMp2htGOoGVD2N1UBilFxtbgFZl5vn66BKDF1vXzp7gu+AOrvgB9O+HRkAOfj8GKo5FIOzMtRfW9juAw==
  template:
    metadata:
      name: qbittorrent-vpn
      namespace: media
    type: Opaque
