apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: node-problem-detector
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: node-problem-detector
      sourceRef:
        kind: HelmRepository
        name: deliveryhero
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: false
    resources:
      requests:
        cpu: "20m"
        memory: "64Mi"
      limits:
        cpu: "100m"
        memory: "128Mi"
    settings:
      log_monitors:
        - /config/kernel-monitor.json
        - /config/systemd-monitor.json
      custom_plugin_monitors: []
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
