apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kured
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: kured
      sourceRef:
        kind: HelmRepository
        name: kured
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    configuration:
      # Maintenance reboot window: 2 AM - 5 AM
      startTime: "2:00"
      endTime: "5:00"
      timeZone: "UTC"
      # Prevent all nodes from rebooting at once
      concurrency: 1
      # Reboot on unschedulable nodes
      rebootSentinelCommand: ""
      # Period to check for sentinel file
      period: "1h"
      # Annotate nodes after reboot for post-reboot handler
      annotateNodes: true
    metrics:
      enabled: true
      service:
        port: 8080
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "8080"
    resources:
      requests:
        cpu: "10m"
        memory: "32Mi"
      limits:
        cpu: "50m"
        memory: "64Mi"
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
