apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kubernetes-event-exporter
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: kubernetes-event-exporter
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
        # Optionally pin a version, e.g.:
        # version: 3.2.0
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    resources:
      requests:
        cpu: "25m"
        memory: "64Mi"
      limits:
        cpu: "100m"
        memory: "128Mi"
    config:
      logLevel: info
      logFormat: json
      receivers:
        - name: loki
          loki:
            streamLabels:
              job: kubernetes-event-exporter
            url: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push
            labels:
              namespace: "{{ .InvolvedObject.Namespace }}"
              reason: "{{ .Reason }}"
              type: "{{ .Type }}"
              kind: "{{ .InvolvedObject.Kind }}"
              name: "{{ .InvolvedObject.Name }}"
      route:
        routes:
          - match:
              - receiver: loki
