apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubernetes-event-exporter
  namespace: monitoring
spec:
  interval: 10m
  releaseName: kubernetes-event-exporter
  chartRef:
    kind: OCIRepository
    name: kubernetes-event-exporter
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    resources:
      requests:
        cpu: "25m"
        memory: "64Mi"
      limits:
        cpu: "100m"
        memory: "128Mi"
    config:
      logLevel: info
      logFormat: json
      receivers:
        - name: loki
          loki:
            streamLabels:
              job: kubernetes-event-exporter
            url: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push
            labels:
              namespace: "{{ .InvolvedObject.Namespace }}"
              reason: "{{ .Reason }}"
              type: "{{ .Type }}"
              kind: "{{ .InvolvedObject.Kind }}"
              name: "{{ .InvolvedObject.Name }}"
      route:
        routes:
          - receiver: loki
