apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: loki
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 10m
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  dependsOn:
    - name: kube-prometheus-stack
      namespace: monitoring
  values:
    # Use single binary mode for resource-constrained homelab
    deploymentMode: SingleBinary
    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      storage:
        type: filesystem
      schemaConfig:
        configs:
          - from: "2020-01-01"
            store: tsdb
            object_store: filesystem
            schema: v13
            index:
              prefix: index_
              period: 24h
      limits_config:
        retention_period: 168h
        ingestion_rate_mb: 4
        ingestion_burst_size_mb: 6
        max_streams_per_user: 10000
        max_global_streams_per_user: 10000
    singleBinary:
      replicas: 1
      resources:
        requests:
          cpu: "50m"
          memory: "128Mi"
        limits:
          cpu: "250m"
          memory: "512Mi"
      persistence:
        enabled: true
        size: 10Gi
    # Disable components not needed in single binary mode
    backend:
      replicas: 0
    read:
      replicas: 0
    write:
      replicas: 0
    gateway:
      enabled: false
    # Disable test pod
    test:
      enabled: false
    # Enable monitoring
    monitoring:
      selfMonitoring:
        enabled: false
        grafanaAgent:
          installOperator: false
      lokiCanary:
        enabled: false
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: promtail
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: promtail
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 10m
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  dependsOn:
    - name: loki
      namespace: monitoring
  values:
    config:
      clients:
        - url: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push
      snippets:
        pipelineStages:
          - cri: {}
    resources:
      requests:
        cpu: "25m"
        memory: "64Mi"
      limits:
        cpu: "100m"
        memory: "128Mi"
    tolerations:
      - operator: Exists
