# Probe for Kaneo
# Monitors HTTPS endpoint availability and response time
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: kaneo
  namespace: monitoring
  labels:
    app: kaneo
    release: kube-prometheus-stack
spec:
  jobName: kaneo
  prober:
    url: kube-prometheus-stack-prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115
  module: http_2xx
  targets:
    staticConfig:
      static:
        - https://kaneo.homelab
  interval: 60s
  scrapeTimeout: 10s
