---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCR/FyJ/H+zc9eUhe4cnkcj96R8soJU41ULCCmwC65ccTOMnxeNIqpzoXb1z+eaS6miwPvO8/jlyIOcqq1suDnFfOPl2inkvnrjBqo/pTuK9ECuljcb7qgeU8VmllN8T1p8fNkcZtl4WpZRwVu6LAOA/YPnVnkJUyOh3J49VECr1IMuMdUgcA6kgyQ0itMAAJWu9VlIpkiCVvxxnVSxKytTu4Js27NtY709vVm3qX7oQsJPBbZtEEfkexiunlcclVleemc4/6067e2r2+pgRkfN7VuH2SBHqM32u9g1zBTffru756WZy+a5H+q747yM+APSS3TokR1jDxwDKAeeEKwGV0D0RAvBb48sFnsglGdtEs/QEwmT3MA5ArBtf4IAAJ5wzIzmtEZqievIa1DfyYMac5+ch7YYZ8GYTsbSBYfdaRxHLNOc9eAvnwuSJJFpUkaPOSvXg+8OsOaLoTFAvIGm9llguP4K6wvv/3j1TR0fh89Q9lCDIsagcegef/inE66ZzL6eTEoE5Ysof1qQbcMsJP7t4tRv1Gbwz3qwsTEswPn9dIBXztGGNIl/T629bxaZoqg8lMnGRkXDQg3BgBUtXBjCpS0YXVkKicrVRQwD40h9jVzlN/CEfp4XZU2JuCSqS/kTQqy7OPLAyc2FI/MQ4gAL2jz9TA3YVoZ8zuwGElGjWK3/s1IsEj/Gy4UJYiTwvxQZw2UYdpE=
    admin-user: AgBPiF5aJWyje03jsOdeqQSepQTy8CZJ4ZYs5lfzkIRJognRTBo7MfyG8kzyfg+kJwSRQdwGQCi8PU8QDxPqyUCaN5g3eT9uAvKjXmxsU3DFb/fFRy1ws+ioYQNesLVuPYuO6oxtd3STT2LJhEGCvOR2T3D8JDx+MjJbQ2kf33FlU2ZCjgzlwnO8VO53FiUBN+aWxmMoZuZ8+0HwJ6eWvvu8qx0kfTjJPSEdYlzZbHEmALy+qyTAzVXWobKc7hV8lc3jotw3Rhps3XcCtG+F0r8g78v6CNXA+0A+zCL2nvX+/R8aJWec30vFuc2ixFpP6TMrBPvgzN7ofcrAYQjDk1z3QHX0nbX/erjxt+Gi02Ti+PKDExzOrfeMUKn8Ntze52dsZt9ehoTQYD76slvLRz/NB1yzCHCL4FcDuYnZ/LUYhUKySW21TIgLZ6ZybR6MwS98fzdnJkwT3ldJFBClh1oYHAi9jm0Ig4bTyJ2bQ7EPNCoRLXBrxX2T82lZZNPyuWA2l3+bpnCSASYhbNZ0fpZsYoUXisHuXVanVBSlL9j9hszzsc4wwkjpvpuqbVUGDzpgFw9AtzgIjnGP8UmIg+hu05C8yjwc59QycqcnLQCfV8pmwtUCLydWgrX99Leeb5Z1wO7ihMtMSScfm9Hjsmf8tb11u/MgF99GqkYet3CFrnERGnKekRTF1HLPn8qLneBNd67Xqg==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
    type: Opaque
