apiVersion: v1
kind: Namespace
metadata:
  name: kyverno
  labels:
    name: kyverno
    environment: production
    owner: rishik
    app.kubernetes.io/name: kyverno
    app.kubernetes.io/component: policy-engine
