---
# This is a template for the sealed secret.
# To create the actual sealed secret, run:
#
# kubectl create secret generic hardcover-sync-credentials \
#   --namespace=media \
#   --from-literal=HARDCOVER_API_KEY="your-hardcover-api-key" \
#   --from-literal=BOOKSHELF_API_KEY="your-bookshelf-api-key" \
#   --dry-run=client -o yaml | \
# kubeseal --format yaml \
#   --controller-name=sealed-secrets \
#   --controller-namespace=flux-system \
#   > apps/hardcover-sync/sealedsecret-hardcover-sync-credentials.yaml
#
# Replace this file with the output from the above command.
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hardcover-sync-credentials
  namespace: media
spec:
  encryptedData:
    HARDCOVER_API_KEY: REPLACE_WITH_SEALED_VALUE
    BOOKSHELF_API_KEY: REPLACE_WITH_SEALED_VALUE
  template:
    metadata:
      name: hardcover-sync-credentials
      namespace: media
