apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kaneo
  namespace: flux-system
spec:
  interval: 1h
  url: https://github.com/usekaneo/kaneo
  ref:
    # renovate: datasource=github-tags depName=usekaneo/kaneo
    tag: v2.9.8
