# ClusterRoleBinding for RWX PVC management
# Binds the rwx-pvc-manager ClusterRole to appropriate service accounts
# Add service accounts here that need to manage RWX storage
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rwx-pvc-manager-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rwx-pvc-manager
subjects:
  # Flux system service account for GitOps management
  - kind: ServiceAccount
    name: kustomize-controller
    namespace: flux-system
  - kind: ServiceAccount
    name: helm-controller
    namespace: flux-system
