---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homebox
  namespace: homebox
spec:
  suspend: false
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: "4.6.2"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 30m
  install:
    createNamespace: false
    remediation:
      retries: 3
    timeout: 15m
  upgrade:
    remediation:
      retries: 3
    timeout: 15m
  values:
    controllers:
      homebox:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: ghcr.io/sysadminsmedia/homebox
              tag: main
            env:
              - name: HOMEBOX_ALLOW_REGISTRATION
                value: "true"
              - name: HOMEBOX_LOG_LEVEL
                value: "info"
              - name: TZ
                value: "UTC"
            resources:
              requests:
                cpu: "50m"
                memory: "128Mi"
              limits:
                cpu: "500m"
                memory: "512Mi"

    service:
      app:
        controller: homebox
        ports:
          http:
            port: 7745

    persistence:
      data:
        enabled: true
        storageClass: longhorn
        accessMode: ReadWriteOnce
        size: 5Gi
        globalMounts:
          - path: /data
