---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homebox-credentials
  namespace: homebox
spec:
  encryptedData:
    api-key-pepper: AgBlGDgnA10jLR0d/AIHUSlWZRRJSRZsm+IVhh2yXPhijDXLQAwG+oUwFmrQ2KpbSNeSu0t3dwNM6qPYiF3iPT9Fe8LdpUR5BBygfn/xpA3Jx248qU43i7ugXTL3ur3w4WDPABYkRhIMLXdJEwg3IgQGmLEfgKHBWz8aCC/VXcJl5WfhXwTYkmfUmT4+ILBs8+luYJMP/KWIIcmnPAFT2tnr4F/JCI6vMMN6E106mVTfFLVFuCxRJk9fzkv592HHS22NTy/WxXN+1woWihsSGA6xhNbRf5IWZaZ/drKtNZjgvAryFSyVbGNStkLwXzyunnMcos4S9+Cbez0Sl8eIT3UccN17WdMpy2OdOai1JVWp2zb9B2y52GJf5XcO0t5ZqGMzbpmfe5BBskDjSMEm5PS01I+m+4knXGY+HfzE1JEpldD9fNUHCrTvjz9l7iHoKRXG9X0gChJnT3rWaEUbOjP9F76AzmrXBM/5qhre+D8R6RlMPVbQAQzvBMAbUz258avA0no6SwWK27YxHdbcpyj8CA/1KSXCzpEU3FO75SdbKp1EYARFRUZbAakOZCBT36m++seJeRk/TukariuM1z16qCu5OpJvaXbbg8vE3p9c5np7xy+DNu+DTBJGg9m4IIhK0khj/JNKImO0QdNZS8Yutfh/rSM6uzV4xOzf8iytgZhZ7t/xiP+GQLZm+Kt0kWOwJ+wJoU0e1vSPPbUzK/OSKY8bpsJrD4l9h9dj3okdYODbFMLn7kr4CH01LORKgZkeYvi73rVFFSEL/FYjfD+c
  template:
    metadata:
      name: homebox-credentials
      namespace: homebox
