---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: syncthing
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: "3.5.1"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 30m
  install:
    createNamespace: false
    remediation:
      retries: 3
    timeout: 15m
  upgrade:
    remediation:
      retries: 3
    timeout: 15m
  values:
    controllers:
      syncthing:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch

        containers:
          app:
            image:
              repository: syncthing/syncthing
              tag: 2.0.14
            args:
              - serve
              - --home=/config
              - --gui-address=0.0.0.0:8384
              - --no-default-folder
            env:
              TZ: America/Los_Angeles
              # Ignore permissions - required for storage that doesn't support chmod
              STNOUPGRADE: "true"
            ports:
              - name: http
                containerPort: 8384
                protocol: TCP
              - name: sync-tcp
                containerPort: 22000
                protocol: TCP
              - name: sync-udp
                containerPort: 22000
                protocol: UDP
              - name: discovery
                containerPort: 21027
                protocol: UDP
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: "50m"
                memory: "128Mi"
              limits:
                cpu: "500m"
                memory: "512Mi"
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /rest/noauth/health
                    port: 8384
                  initialDelaySeconds: 30
                  periodSeconds: 30
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /rest/noauth/health
                    port: 8384
                  initialDelaySeconds: 30
                  periodSeconds: 10
                  failureThreshold: 3
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /rest/noauth/health
                    port: 8384
                  initialDelaySeconds: 5
                  periodSeconds: 5
                  failureThreshold: 30

    service:
      app:
        controller: syncthing
        type: ClusterIP
        ports:
          http:
            port: 8384
      sync:
        controller: syncthing
        type: LoadBalancer
        ports:
          sync-tcp:
            port: 22000
            protocol: TCP
          sync-udp:
            port: 22000
            protocol: UDP
          discovery:
            port: 21027
            protocol: UDP

    ingress:
      app:
        enabled: true
        className: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"
        hosts:
          - host: syncthing.homelab
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - syncthing.homelab
            secretName: syncthing-tls

    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: longhorn
        globalMounts:
          - path: /config
      # Books sync folder - syncs to the calibre library
      books:
        enabled: true
        type: hostPath
        hostPath: /media/rishik/Expansion/books
        globalMounts:
          - path: /data/books

    defaultPodOptions:
      nodeSelector:
        kubernetes.io/hostname: rishik-worker1
