# Allow monitoring namespace (Prometheus) to scrape metrics from pods
# This enables the kube-prometheus-stack to collect metrics cluster-wide
# Note: Ports listed cover common metrics endpoints. Applications should
# expose metrics on these standard ports for scraping to work correctly.
#
# Usage: Copy this NetworkPolicy to other namespaces by changing the
# metadata.namespace field or using Kustomize namespace transformers
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-monitoring-scrape
  namespace: default
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
      ports:
        # Prometheus server
        - protocol: TCP
          port: 9090
        # Node exporter
        - protocol: TCP
          port: 9100
        # Common application metrics port
        - protocol: TCP
          port: 8080
        # HTTPS metrics endpoint
        - protocol: TCP
          port: 8443
        # Pushgateway
        - protocol: TCP
          port: 9091
        # Alertmanager
        - protocol: TCP
          port: 9093
        # Alertmanager cluster
        - protocol: TCP
          port: 9094
