---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-tls
  namespace: siloarr
spec:
  secretName: vault-tls
  issuerRef:
    name: cluster-ca
    kind: ClusterIssuer
  commonName: vault.homelab
  dnsNames:
    - vault.homelab
