---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stash-config
  namespace: siloarr
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
