apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paperless
  namespace: paperless
spec:
  interval: 30m
  chart:
    spec:
      chart: charts/paperless-ngx
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 30m
  install:
    createNamespace: false
    remediation:
      retries: 3
    timeout: 10m
  upgrade:
    remediation:
      retries: 3
    timeout: 10m
  values:
    # Use pinned version, not latest
    image:
      tag: "2.13.5"

    # Environment variables are already set in chart defaults
    # No need to override unless different from defaults

    # Persistence sizes match current deployment
    persistence:
      data:
        size: 5Gi
      media:
        size: 20Gi
      export:
        size: 5Gi
      consume:
        size: 5Gi

    # PostgreSQL configuration
    postgresql:
      persistence:
        size: 8Gi

    # Redis configuration
    redis:
      persistence:
        size: 1Gi

    # Resource limits
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: "1"
        memory: 2Gi
