# Placeholder SealedSecret for Paperless-ngx credentials
#
# This file contains placeholder values. You MUST replace these with your own sealed secrets.
#
# Required secrets:
# 1. postgresql-password: PostgreSQL database password for paperless_user
# 2. paperless-secret-key: Secret key for Django (64+ character random string)
# 3. paperless-admin-password: Admin credentials for the Paperless-ngx web interface
#
# To create the actual sealed secret, run this command:
#
# kubectl create secret generic paperless-credentials \
#   --namespace=paperless \
#   --from-literal=postgresql-password="$(openssl rand -base64 32)" \
#   --from-literal=paperless-secret-key="$(openssl rand -base64 64 | tr -d '\n')" \
#   --from-literal=paperless-admin-password="$(openssl rand -base64 32)" \
#   --dry-run=client -o yaml | \
# kubeseal --format yaml \
#   --controller-name=sealed-secrets \
#   --controller-namespace=flux-system \
#   > apps/paperless-ngx/sealedsecret-paperless-credentials.yaml
#
# See docs/sealed-secrets.md for more information on working with sealed secrets
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: paperless-credentials
  namespace: paperless
spec:
  encryptedData:
    # REPLACE THESE WITH YOUR OWN SEALED VALUES
    postgresql-password: PLACEHOLDER_REPLACE_WITH_SEALED_VALUE
    paperless-secret-key: PLACEHOLDER_REPLACE_WITH_SEALED_VALUE
    paperless-admin-password: PLACEHOLDER_REPLACE_WITH_SEALED_VALUE
  template:
    metadata:
      name: paperless-credentials
      namespace: paperless
    type: Opaque
