apiVersion: v1
kind: Service
metadata:
  name: paperless-keda-interceptor
  namespace: paperless
spec:
  type: ExternalName
  externalName: keda-add-ons-http-interceptor-proxy.keda.svc.cluster.local
  ports:
    - name: http
      port: 8080
      targetPort: 8080
