# Placeholder SealedSecret for Kindle Sender credentials
#
# This file contains placeholder values. You MUST replace these with your own sealed secrets.
#
# Required secrets:
# 1. SMTP_HOST: SMTP server hostname (e.g., smtp.gmail.com)
# 2. SMTP_PORT: SMTP server port (e.g., 587 for STARTTLS, 465 for TLS/SSL)
# 3. SMTP_USER: SMTP authentication username
# 4. SMTP_PASSWORD: SMTP authentication password
# 5. KINDLE_EMAIL: Your Kindle email address (e.g., username@kindle.com)
# 6. SENDER_EMAIL: Email address to use as sender (usually same as SMTP_USER)
#
# To create the actual sealed secret, run this command:
#
# kubectl create secret generic kindle-sender \
#   --namespace=media \
#   --from-literal=SMTP_HOST="smtp.gmail.com" \
#   --from-literal=SMTP_PORT="587" \
#   --from-literal=SMTP_USER="your-email@gmail.com" \
#   --from-literal=SMTP_PASSWORD="your-app-password" \
#   --from-literal=KINDLE_EMAIL="your-kindle@kindle.com" \
#   --from-literal=SENDER_EMAIL="your-email@gmail.com" \
#   --dry-run=client -o yaml | \
# kubeseal --format yaml \
#   --controller-name=sealed-secrets \
#   --controller-namespace=flux-system \
#   > apps/kindle-sender/sealedsecret-kindle-sender.yaml
#
# See docs/sealed-secrets.md for more information on working with sealed secrets
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kindle-sender
  namespace: media
spec:
  encryptedData:
    # REPLACE THESE WITH YOUR OWN SEALED VALUES
    SMTP_HOST: PLACEHOLDER_REPLACE_WITH_SEALED_VALUE
    SMTP_PORT: PLACEHOLDER_REPLACE_WITH_SEALED_VALUE
    SMTP_USER: PLACEHOLDER_REPLACE_WITH_SEALED_VALUE
    SMTP_PASSWORD: PLACEHOLDER_REPLACE_WITH_SEALED_VALUE
    KINDLE_EMAIL: PLACEHOLDER_REPLACE_WITH_SEALED_VALUE
    SENDER_EMAIL: PLACEHOLDER_REPLACE_WITH_SEALED_VALUE
  template:
    metadata:
      name: kindle-sender
      namespace: media
    type: Opaque
